### ISSUE TITLE
Fontain area. Round or square???

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#128]
I can't understand in original game fontain area square 10x10 or circle R=10. Thanks.

**Comment by gecube** [comment]
1. Fountains area is square
2. Fountains area has radius equal to 5(4) tiles. 9 tiles is diameter, because fountain is placed in center of square.
3. The size of fountain area depends on map type. [In deserts, fountain radius is smaller](http://caesar3.heavengames.com/strategy/housing/block03.shtml).

**Comment by dalerank** [comment]
1. Correct me pls (original caesar3)
   ![21](https://f.cloud.github.com/assets/918081/628782/8cde1cf2-d0f3-11e2-983a-f9e5bfd10a40.png)

2/3. i know

**Comment by Rovanion** [comment]
@dalerank Could that be because of the 2x2 buildings?

**Comment by gecube** [comment]
@Rovanion, As I know if one tile of multi-tile building is supplied with water (well or fountain), then all building is connected to water source.

**Comment by dalerank** [comment]
hm... it need more expensive alg that i think, i'm go to play caesar3)))

**Comment by dalerank** [comment]
Fixed. Square area.
