### ISSUE TITLE
Desirability influence. How???

### ISSUE THREAD

**Issue by dalerank** [gecube/opencaesar3#129]
How Desirability influence to round area, by constant value or gradient ( from center to border )???

**Comment by gecube** [comment]
Desirability for buildings is stored in model configuration file as two values: start value of DES and step. Step is difference betweeb desirability when you take next cell from starting tile. Also step can be negative value. It means that near the building DES effect may be negative, but in long distance - positive. Like with Market.

So when we will count desirability influence effect we must unroll these two values into array of 6 values: each is DES effect for every tile from original building, also in original game DES effect of building lasts only for distance 6 due to performance issues. 

If my explanation isn't clear, please find more comprehensive description how desirability works on games fans sites.

Thanks

**Comment by dalerank** [comment]
ok... it good description, thanks

**Comment by gecube** [comment]
@dalerank, please look through the link: http://www.gamefaqs.com/pc/63635-caesar-iii/faqs/14466 or [here](http://caesar3.heavengames.com/cgi-bin/caeforumscgi/display.cgi?action=ct&f=2,3600,,all)
There is comprehensive description how desirability works. Also I want to propose enhancement to original gameplay: in original game influence range is 6 tiles, but some buildings have greater values in model file, so, as now computers are fast, we can remove cap of influence range.
