### ISSUE TITLE
same conventions

### ISSUE THREAD

**Issue by gathanase** [gecube/opencaesar3#9]
Hi
There should be a single coding convention, accepted and used by all.
- The usage of #include <foo> vs #include "foo"
- The file names "foo.hpp" vs "oc3_foo.h"
- The usage of tabs vs spaces
- The names "#define _FOO" vs "#define __OPENCAESAR3_FOO_H_INCLUDE_"
- Indent spaces
- ...
  For indentation, maybe we can improve the "make format" rule and use it.

I understand that all developers have preferences or habits, but we must choose and enforce a single coding convention.

Thanks!

**Comment by captnfab** [comment]
Agreed.
How can we decide on that ?

Here are my preferences :
1. #include "foo" for local headers and < foo > for system lib
2. .h headers
3. use of two spaces instead of tabs
4. #define _FOO_H_

For what concern the coding style, my preferences goes to GNU standard : https://en.wikipedia.org/wiki/GNU_Coding_Standards

Anyway, I'm flexible. I would simply prefer to avoid tabs :)

**Comment by gecube** [comment]
Good!
1. About headers. I prefer to use brackets (#include <foo>) for standard libraries headers and quotes (#include "foo_user") for user headers.
2. I don't care.
3. I prefer spaces, because I use Kate editor. So indentation is multiple of two.
4. > The names "#define _FOO" vs "#define __OPENCAESAR3_FOO_H_INCLUDE_"
Don't care. Header guards are used only once. So it doesn't make sense. Also we can use #pragma once directive. But it may be non-compatible with different compilers.

**Comment by gecube** [comment]
Also I want to talk about development tools. I use Kate as editor, makefile + gcc compiler. And have some issues with compiling of @dalerank's code, because he is using MSVS. I understand that everybody is free to choose tools that are more convenient for each one, but we don't need to struggle with limitations of every environment :-) What do you think?

**Comment by gathanase** [comment]
if I am not mistaken, gcc cannot compile for win32 so we need to be compatible with mingw32 or MSVS.

**Comment by dalerank** [comment]
Hi!
1. About headers. Usually i use quotes in #include
2. It only name, if you want it maybe .hxx
3. Spaces, because I use Notepad++ editor (MSVS Exspress(as compiler) + Tomanote++(as refactoring/code style tool)). Tabs for makefile only, IMHO.
4. The names "#define FOO" vs "#define __OPENCAESAR3_FOO_H_INCLUDE". It only include guards, dont care. But my editor place this string such filename+projectname )))

**Comment by gecube** [comment]
@gathanase, mingw32 contains gcc/g++ :-) Also there is option for crosscompilation, so I can build windows executable on linux machine.

**Comment by gathanase** [comment]
Yes i was able to compile for windows from linux also, but mingw-g++ and gcc produce a slightly different game (for example the thousand separator in sprintf did not work the same on my last test, if I remember correctly that was the only visible difference).
I would prefer to compile with a very similar compiler for linux and windows, if mingw32 does the job let's use it only and dismiss all other compilers.

**Comment by captnfab** [comment]
If we want oc3 to be distributed by distros such as Debian or Ubuntu, the game has to at least compile with gcc (and maybe with clang too...)

**Comment by gathanase** [comment]
Thanks for your input!
We will use:
- oc3_foo.cpp and oc3_foo.hpp files
- #include "foo" for locals and #include <foo> for system
- 2 spaces for indent, no tabs

I just committed many files to enforce the filename and include conventions.
