### ISSUE TITLE
Question/Suggestion

### ISSUE THREAD

**Issue by avarisclari** [gecube/opencaesar3#97]
Wouldn't it be less likely to get in trouble to require the files from the original Caesar 3? Or do we actually need them already and that's what the resources file is?

**Comment by gasobi** [comment]
Hello!

I will answer you.
1. Maybe you know that when old games are rewritten, they use resources from original game. It is convenient way to make things work. But it has only one disadvantage: you need to buy copy of original game. I don't know if Caesar III may be bought now through Steam and other stores. But there is possibility to get original game from ebay. 
2. So we need to repack resources from original game to format which is used by opencaesar3. Of course, there are no need to do it manually, because install script and instruction how to make resources compatible are written.
3. For simplifying life resulting archive of binary files was placed by [link](https://github.com/gecube/opencaesar3/tree/master/resources).
4. Without resources file opencaesar won't work. They are necessary.
5. If you wish you can try to contact with copyrights holders. I think that such old game must be in public domain (like Quake, Doom, Civilization and so on), because owners of label will not make any serious money from such old stuff in any case.

**Comment by JanSimek** [comment]
> I think that such old game must be in public domain (like Quake, Doom, Civilization and so on)

It is not and neither are those other games you mentioned. We will have to wait a few more decades for that to happen. 

> owners of label will not make any serious money from such old stuff

The same copyright owners shut down open-source Starcraft engine just a few years ago and it did not even redistribute original game files. Also, GOG.com still sells it for three bucks. While I am sure they only make peanuts out of it, they are not charity and wouldn't be happy if somebody distributed C3 for free.

btw, this is a great project. I am looking forward to see it progress.

**Comment by Rovanion** [comment]
> Wouldn't it be less likely to get in trouble to require the files from the original Caesar 3? Or do we actually need them already and that's what the resources file is?

Yes the resources file is a collection of files from the original Caesar 3 with some additions.

And it is much more likely that a project gets in trouble if it uses files from some other proprietary product than if it doesn't. Clean room reverse engineering is absolutely legal. Using someone else's assets in a reverse engineered project: okey for private use it seems.

The end goal for many projects that clone or reverse engineer a game is to build it's own assets. But that requires a lot of time and good artists. Using the original assets seems to be the best way to get a project like this one off the ground.

**Comment by gecube** [comment]
> Also, GOG.com still sells it for three bucks

I think this price is good for ability to at least play in native build of Caesar III for Linux system :-) and without restrictions from original game.

> The end goal for many projects that clone or reverse engineer a game is to build it's own assets

Yes, own assets are good, but at least we must have working code. Sprites, music and other resources can be made at any time, but now we must focus on code.
